### PR TITLE
64 improve reproducibility

### PR DESCRIPTION
**Pull request by Robinlovelace**
- Add files to tests folder
- Move more files
- Update paper

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads up @JosiahParry this will need some set-up on the Python side I imagine but good start for build on every commit paper..

**Comment by JosiahParry** [comment]
it might be easier to try and get GHA to work off of a container itself https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by Robinlovelace** [comment]
> it might be easier to try and get GHA to work off of a container itself https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

Possibly, but Docker is a pain also. Open to ideas to get this passing!

**Comment by Robinlovelace** [comment]
I'm thinking while watching all these dependencies install/fail: too many deps, we need a cleaner + leaner approach + ecosystem, not the monolith that is `{splanr}` : ( Despite splitting things out, it is very bloated.

**Pull request merged**
