### PR TITLE
Paper zw

### PR DESCRIPTION
**Pull request by wangzhao0217**
- update will apporach
- update
- update methodology of simple network
- add pics
- update
- update

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Thanks Zhao, will take a look this morning.

**Comment by Robinlovelace** [comment]
Looks good, I can reproduce locally

image

**Comment by wangzhao0217** [comment]
Hi Robin , I don't have problem to render but I removed the Eval = false
from line 409. Should be okay.

**Comment by Robinlovelace** [comment]
Good job, I'm planning to make a few more tweaks...

**Pull request merged**
