### PR TITLE
restructure section 5

### PR DESCRIPTION
**Pull request by wangzhao0217**
- restructure section 5
- update section 5

### CODE REVIEW

**Comment by wangzhao0217** [comment]
Hi Robin, 

Could you please review the latest pull request? In it, I've restructured Section 5. Given that plotting Doncaster rail and Armley Road didn't seem to add significant value, I've omitted these elements. Please correct me if I am wrong. 
Instead, the section now presents a practical example, focusing on demonstrating the entire implications process using a more complex example. This approach should offer a clearer and more impactful illustration of our objectives.

**Review by Robinlovelace — COMMENTED** [review]
Taking a look at this now..

Before:

image

**Comment by Robinlovelace** [comment]
After:

image

I don't think this is much of an improvement. I will merge this PR, after restoring the Leeds rail example which may be useful in the future, and look to improve the figure further. The priority I think @wangzhao0217 should be on adding new references and fixing bugs in the paper like the "?(caption)" bit in the table that is produced by code in this PR.

**Review by Robinlovelace — COMMENTED** [review]
This new figure is good.

image

**Review by Robinlovelace — APPROVED** [review]

**Pull request merged**
